name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: kustomize build | conftest test -o github -i yaml --combine -
        # expect conftest exits with an error
        continue-on-error: true
